### ISSUE TITLE
博客插图

### ISSUE THREAD

**Issue by bozhangxl** [Draveness/Analyze#34]
Hi，看你博客中的插图很nice。

图一：
![图一](https://cloud.githubusercontent.com/assets/5125500/23832498/49cdfff6-0770-11e7-9bca-e42abc1a262d.png)

图二：
![image](https://cloud.githubusercontent.com/assets/5125500/23832511/87b82774-0770-11e7-975f-8b4b3d2ebf13.png)

请教一下，图1 和 图2 分别是用什么软件绘制的? 谢谢！

**Comment by Draveness** [comment]
Paper 50
Sketch

**Comment by xilin** [comment]
Google了一下Paper 50好像找不到？

**Comment by JakeLin** [comment]
是一个iPad app

**Comment by xilin** [comment]
@JakeLin iPad上也只能搜到Paper by 53?

**Comment by Draveness** [comment]
是这个

Regards,
Draveness

**Comment by xilin** [comment]
@Draveness thx!

**Comment by qinix** [comment]
@Draveness 你是用 Paper 53 的那根笔写的吗？

**Comment by Draveness** [comment]
Apple Pencil
