### ISSUE TITLE
ReactiveObjC内的流程图使用什么软件绘制？

### ISSUE THREAD

**Issue by oxape** [Draveness/analyze#49]
![racchannelto-and-property](https://user-images.githubusercontent.com/8132919/29010027-fc525f60-7b5a-11e7-96c9-f32ac34b1c4f.png)

觉得这种图在分析程序结构时很有用，所以想知道用来绘制的软件，请赐教。
我只知道visio

**Comment by qiushi0908** [comment]
这个keynote好像就能做 @oxape

**Comment by Draveness** [comment]
这问题问过 800 遍了 #28 再也不回答了
